package a.b.d.a;

import com.xiaopeng.device.communication.R;
/* loaded from: classes.dex */
public final class j {
    public static final int A = 4;
    public static final int A0 = 15;
    public static final int A1 = 0;
    public static final int B = 5;
    public static final int B0 = 16;
    public static final int B1 = 1;
    public static final int C1 = 2;
    public static final int D0 = 1;
    public static final int E0 = 5;
    public static final int F = 0;
    public static final int F0 = 7;
    public static final int G = 1;
    public static final int H0 = 0;
    public static final int I0 = 1;
    public static final int K = 0;
    public static final int M0 = 0;
    public static final int N0 = 1;
    public static final int O = 0;
    public static final int O0 = 2;
    public static final int P = 1;
    public static final int P0 = 3;
    public static final int Q = 2;
    public static final int Q0 = 4;
    public static final int R = 3;
    public static final int S = 4;
    public static final int T = 5;
    public static final int T0 = 0;
    public static final int U = 6;
    public static final int U0 = 8;
    public static final int V = 7;
    public static final int W = 8;
    public static final int W0 = 0;
    public static final int X0 = 2;
    public static final int Y = 0;
    public static final int Y0 = 3;
    public static final int Z = 3;
    public static final int Z0 = 4;
    public static final int a1 = 5;

    /* renamed from: b  reason: collision with root package name */
    public static final int f397b = 0;
    public static final int b0 = 0;
    public static final int b1 = 6;

    /* renamed from: c  reason: collision with root package name */
    public static final int f398c = 1;
    public static final int c0 = 1;
    public static final int c1 = 7;

    /* renamed from: d  reason: collision with root package name */
    public static final int f399d = 2;
    public static final int d1 = 8;
    public static final int e = 3;
    public static final int e0 = 0;
    public static final int e1 = 9;
    public static final int f = 6;
    public static final int f0 = 1;
    public static final int f1 = 10;
    public static final int g = 7;
    public static final int g0 = 2;
    public static final int g1 = 11;
    public static final int h = 8;
    public static final int h0 = 3;
    public static final int h1 = 12;
    public static final int i = 11;
    public static final int i0 = 4;
    public static final int i1 = 13;
    public static final int j = 13;
    public static final int j0 = 5;
    public static final int j1 = 14;
    public static final int k = 15;
    public static final int k1 = 15;
    public static final int l = 18;
    public static final int l0 = 0;
    public static final int l1 = 16;
    public static final int m = 20;
    public static final int m0 = 1;
    public static final int m1 = 17;
    public static final int n = 23;
    public static final int n0 = 2;
    public static final int n1 = 18;
    public static final int o = 24;
    public static final int o0 = 3;
    public static final int o1 = 19;
    public static final int p = 25;
    public static final int p0 = 4;
    public static final int p1 = 20;
    public static final int q = 26;
    public static final int q0 = 5;
    public static final int q1 = 21;
    public static final int r0 = 6;
    public static final int r1 = 22;
    public static final int s = 0;
    public static final int s0 = 7;
    public static final int s1 = 23;
    public static final int t0 = 8;
    public static final int t1 = 24;
    public static final int u = 0;
    public static final int u0 = 9;
    public static final int v0 = 10;
    public static final int w0 = 11;
    public static final int w1 = 0;
    public static final int x = 0;
    public static final int x0 = 12;
    public static final int x1 = 1;
    public static final int y = 2;
    public static final int y0 = 13;
    public static final int y1 = 2;
    public static final int z = 3;
    public static final int z0 = 14;

    /* renamed from: a  reason: collision with root package name */
    public static final int[] f396a = {R.attr.background, R.attr.backgroundSplit, R.attr.backgroundStacked, R.attr.contentInsetEnd, R.attr.contentInsetLeft, R.attr.contentInsetRight, R.attr.contentInsetStart, R.attr.customNavigationLayout, R.attr.displayOptions, R.attr.divider, R.attr.elevation, R.attr.height, R.attr.hideOnContentScroll, R.attr.homeAsUpIndicator, R.attr.homeLayout, R.attr.icon, R.attr.indeterminateProgressStyle, R.attr.itemPadding, R.attr.logo, R.attr.navigationMode, R.attr.popupTheme, R.attr.progressBarPadding, R.attr.progressBarStyle, R.attr.subtitle, R.attr.subtitleTextStyle, R.attr.title, R.attr.titleTextStyle};
    public static final int[] r = {16842931};
    public static final int[] t = {16843071};
    public static final int[] v = new int[0];
    public static final int[] w = {R.attr.background, R.attr.backgroundSplit, R.attr.closeItemLayout, R.attr.height, R.attr.subtitleTextStyle, R.attr.titleTextStyle};
    public static final int[] C = {R.attr.expandActivityOverflowButtonDrawable, R.attr.initialActivityCount};
    public static final int[] D = {16842994, R.attr.buttonPanelSideLayout, R.attr.listItemLayout, R.attr.listLayout, R.attr.multiChoiceItemLayout, R.attr.singleChoiceItemLayout};
    public static final int[] E = {16843033, R.attr.srcCompat};
    public static final int[] H = {16842804, R.attr.textAllCaps};
    public static final int[] I = {16842839, 16842926, R.attr.actionBarDivider, R.attr.actionBarItemBackground, R.attr.actionBarPopupTheme, R.attr.actionBarSize, R.attr.actionBarSplitStyle, R.attr.actionBarStyle, R.attr.actionBarTabBarStyle, R.attr.actionBarTabStyle, R.attr.actionBarTabTextStyle, R.attr.actionBarTheme, R.attr.actionBarWidgetTheme, R.attr.actionButtonStyle, R.attr.actionDropDownStyle, R.attr.actionMenuTextAppearance, R.attr.actionMenuTextColor, R.attr.actionModeBackground, R.attr.actionModeCloseButtonStyle, R.attr.actionModeCloseDrawable, R.attr.actionModeCopyDrawable, R.attr.actionModeCutDrawable, R.attr.actionModeFindDrawable, R.attr.actionModePasteDrawable, R.attr.actionModePopupWindowStyle, R.attr.actionModeSelectAllDrawable, R.attr.actionModeShareDrawable, R.attr.actionModeSplitBackground, R.attr.actionModeStyle, R.attr.actionModeWebSearchDrawable, R.attr.actionOverflowButtonStyle, R.attr.actionOverflowMenuStyle, R.attr.activityChooserViewStyle, R.attr.alertDialogButtonGroupStyle, R.attr.alertDialogCenterButtons, R.attr.alertDialogStyle, R.attr.alertDialogTheme, R.attr.autoCompleteTextViewStyle, R.attr.borderlessButtonStyle, R.attr.buttonBarButtonStyle, R.attr.buttonBarNegativeButtonStyle, R.attr.buttonBarNeutralButtonStyle, R.attr.buttonBarPositiveButtonStyle, R.attr.buttonBarStyle, R.attr.buttonStyle, R.attr.buttonStyleSmall, R.attr.checkboxStyle, R.attr.checkedTextViewStyle, R.attr.colorAccent, R.attr.colorButtonNormal, R.attr.colorControlActivated, R.attr.colorControlHighlight, R.attr.colorControlNormal, R.attr.colorPrimary, R.attr.colorPrimaryDark, R.attr.colorSwitchThumbNormal, R.attr.controlBackground, R.attr.dialogPreferredPadding, R.attr.dialogTheme, R.attr.dividerHorizontal, R.attr.dividerVertical, R.attr.dropDownListViewStyle, R.attr.dropdownListPreferredItemHeight, R.attr.editTextBackground, R.attr.editTextColor, R.attr.editTextStyle, R.attr.homeAsUpIndicator, R.attr.imageButtonStyle, R.attr.listChoiceBackgroundIndicator, R.attr.listDividerAlertDialog, R.attr.listPopupWindowStyle, R.attr.listPreferredItemHeight, R.attr.listPreferredItemHeightLarge, R.attr.listPreferredItemHeightSmall, R.attr.listPreferredItemPaddingLeft, R.attr.listPreferredItemPaddingRight, R.attr.panelBackground, R.attr.panelMenuListTheme, R.attr.panelMenuListWidth, R.attr.popupMenuStyle, R.attr.popupWindowStyle, R.attr.radioButtonStyle, R.attr.ratingBarStyle, R.attr.ratingBarStyleIndicator, R.attr.ratingBarStyleSmall, R.attr.searchViewStyle, R.attr.seekBarStyle, R.attr.selectableItemBackground, R.attr.selectableItemBackgroundBorderless, R.attr.spinnerDropDownItemStyle, R.attr.spinnerStyle, R.attr.switchStyle, R.attr.textAppearanceLargePopupMenu, R.attr.textAppearanceListItem, R.attr.textAppearanceListItemSmall, R.attr.textAppearanceSearchResultSubtitle, R.attr.textAppearanceSearchResultTitle, R.attr.textAppearanceSmallPopupMenu, R.attr.textColorAlertDialogListItem, R.attr.textColorSearchUrl, R.attr.toolbarNavigationButtonStyle, R.attr.toolbarStyle, R.attr.windowActionBar, R.attr.windowActionBarOverlay, R.attr.windowActionModeOverlay, R.attr.windowFixedHeightMajor, R.attr.windowFixedHeightMinor, R.attr.windowFixedWidthMajor, R.attr.windowFixedWidthMinor, R.attr.windowMinWidthMajor, R.attr.windowMinWidthMinor, R.attr.windowNoTitle};
    public static final int[] J = {R.attr.allowStacking};
    public static final int[] L = {16843015, R.attr.buttonTint, R.attr.buttonTintMode};
    public static final int[] M = {R.attr.arrowHeadLength, R.attr.arrowShaftLength, R.attr.barLength, R.attr.color, R.attr.drawableSize, R.attr.gapBetweenBars, R.attr.spinBars, R.attr.thickness};
    public static final int[] N = {16842927, 16842948, 16843046, 16843047, 16843048, R.attr.divider, R.attr.dividerPadding, R.attr.measureWithLargestChild, R.attr.showDividers};
    public static final int[] X = {16842931, 16842996, 16842997, 16843137};
    public static final int[] a0 = {16843436, 16843437};
    public static final int[] d0 = {16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
    public static final int[] k0 = {16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, R.attr.actionLayout, R.attr.actionProviderClass, R.attr.actionViewClass, R.attr.showAsAction};
    public static final int[] C0 = {16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, R.attr.preserveIconSpacing};
    public static final int[] G0 = {16843126, R.attr.overlapAnchor};
    public static final int[] J0 = {R.attr.state_above_anchor};
    public static final int[] K0 = {16842970, 16843039, 16843296, 16843364, R.attr.closeIcon, R.attr.commitIcon, R.attr.defaultQueryHint, R.attr.goIcon, R.attr.iconifiedByDefault, R.attr.layout, R.attr.queryBackground, R.attr.queryHint, R.attr.searchHintIcon, R.attr.searchIcon, R.attr.submitBackground, R.attr.suggestionRowLayout, R.attr.voiceIcon};
    public static final int[] L0 = {16842930, 16843126, 16843131, 16843362, R.attr.popupTheme};
    public static final int[] R0 = {16843044, 16843045, 16843074, R.attr.showText, R.attr.splitTrack, R.attr.switchMinWidth, R.attr.switchPadding, R.attr.switchTextAppearance, R.attr.thumbTextPadding, R.attr.track};
    public static final int[] S0 = {16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, R.attr.textAllCaps};
    public static final int[] V0 = {16842927, 16843072, R.attr.collapseContentDescription, R.attr.collapseIcon, R.attr.contentInsetEnd, R.attr.contentInsetLeft, R.attr.contentInsetRight, R.attr.contentInsetStart, R.attr.logo, R.attr.logoDescription, R.attr.maxButtonHeight, R.attr.navigationContentDescription, R.attr.navigationIcon, R.attr.popupTheme, R.attr.subtitle, R.attr.subtitleTextAppearance, R.attr.subtitleTextColor, R.attr.title, R.attr.titleMarginBottom, R.attr.titleMarginEnd, R.attr.titleMarginStart, R.attr.titleMarginTop, R.attr.titleMargins, R.attr.titleTextAppearance, R.attr.titleTextColor};
    public static final int[] u1 = {16842752, 16842970, R.attr.paddingEnd, R.attr.paddingStart, R.attr.theme};
    public static final int[] v1 = {16842964, R.attr.backgroundTint, R.attr.backgroundTintMode};
    public static final int[] z1 = {16842960, 16842994, 16842995};
}
